In [2]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression as Logit 
from sklearn.cluster import KMeans
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_rows',1000)
pd.set_option('display.max_columns',1000)

In [65]:
#m é a confusion matrix, ind é o indíce da variável que queremos testar
#ind começa em 0
def sensitivity(m,ind):
    if not(len(m)==len(m[0])):
        return 'Erro! A matriz tem ser ser quadrada'
    print('O índice começa em 0')
    x=m[ind][ind]
    n=0
    q=[]
    while n<len(m):
        if n==ind:
            n+=1
        else:
            q+=[m[n][ind]]
            n+=1
    y=sum(q)
    return (x/(x+y))

def specificity(m,ind):
    if not(len(m)==len(m[0])):
        return 'Erro! A matriz tem ser ser quadrada'
    print('O índice começa em 0')
    n=0
    q=[]
    while n<len(m):
        if n==ind:
            n+=1
        else:
            q+=[m[ind][n]]
            n+=1
    x=sum(q)
    f=[]
    i=0
    while i<len(m):
        c=0
        if i==ind:
            i+=1
        else:
            while c<len(m):
                if c==ind:
                    c+=1
                else:
                    f+=[m[i][c]]
                    c+=1
            i+=1
    y=sum(f)
    #print(q,f)  #verifica se os valores q estamos a escolher são os certos
    return (y/(x+y))

#A percentagem de previsões corretas feitas pelo modelo
#i é a linha da confusion matrix (o outcome que queremos ver a percentagem de previsões corretas)
def pred_percent(m,i):
    #print(m)
    if not(len(m)==len(m[0])):
        return 'Erro! A matriz tem ser ser quadrada'
    #print('O índice começa em 0')
    x=m[i][i]
    soma=sum(m[i])
    if soma==0:
        return 'Não previu nada para esta variável'
    else:
        return round((x/soma)*100),'%'

In [243]:
#faz a conf matrix do model (já tem de estar fit())
#o modelo tem de ter a probabilidade ligada
def conf_matrix(model,X_test,y_test,limite=0.5):
    prob=model.predict_proba(X_test)
    Y=list(y_test)
    cmat=np.array([[0,0],[0,0]])   #confusion matrix
    x=0
    y=0
    l=0
    for i in range(len(prob)):
        
        if prob[i][1]>limite:
            print(prob[i],i)
            what=1
        else:
            what=0
        if what==1 and Y[i]==1: #previsão 1 e realidade 1
            x+=X_test.iloc[i]['LowODD']
            l+=1
            cmat[0][0]+=1
            #print((X_test[i:i+1]))
            print(i,'|',X_test.iloc[i]['LowODD'])
        elif what==1 and Y[i]==0: #previsão 1 e realidade 0
            y+=X_test.iloc[i]['LowODD']
            l+=1
            cmat[0][1]+=1
            #print((X_test[i:i+1]),'enganou-se')
            print(i,'|',X_test.iloc[i]['LowODD'],'wrooooooooooooong')
        elif what==0 and Y[i]==1:  #previsão 0 e realidade 1
            cmat[1][0]+=1
        elif what==0 and Y[i]==0:  #previsão 0 e realidade 0
            cmat[1][1]+=1
        else:
            print('Erro em conf_matrix')
    print(l)
    if l>0:
        print((x+y)/l)
    return (cmat,
           pred_percent(cmat,0))



_______________________________________________

In [47]:
len(biglion.index)

1048

In [3]:
biglion=pd.read_excel('BigLion.xlsx',0)
Xbiglion=biglion.drop(['Div','Date','Time','LO_Team','HO_Team','Won/NotWon',],axis=1)
Ybiglion=biglion['Won/NotWon']
#X_bigtrain=pd.concat([Xbiglion[:700],Xbiglion[740:]],sort=False)
#y_bigtrain=pd.concat([Ybiglion[:700],Ybiglion[740:]],sort=False)
X_bigtrain=Xbiglion[:1010]
y_bigtrain=Ybiglion[:1010]
X_bigtest=Xbiglion[1010:]
y_bigtest=Ybiglion[1010:]

In [4]:
Mbig1=SVC(C=0.0001,kernel='rbf',probability=True)
Mbig1.fit(X_bigtrain,y_bigtrain)

C:\Users\joaom\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=0.0001, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=True, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [5]:
Mbig2=Logit(C=0.0005)
Mbig2.fit(X_bigtrain,y_bigtrain)

C:\Users\joaom\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=0.0005, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [10]:
Mbig3=KMeans(n_clusters=2)
y_predicted=Mbig3.fit_predict(X_bigtest)
y_predicted

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1])

In [12]:
list(y_bigtest)

[1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1]

In [256]:
Modd1.predict_proba([[10,3,3,1.15,6.95,14.07,1.6,2.12,15,0,10.4,10.6,4.4,4.4,1.6,
                2,1.333,1,1,1,1,7,1,-18,10,9,4,4,1,2,0,1,10,0,13]])

array([[0.08905263, 0.91094737]])

In [244]:
conf_matrix(Mbig1,X_bigtest,y_bigtest,limite=0.5)

[0.48020296 0.51979704] 0
0 | 2.69
[0.49421776 0.50578224] 3
3 | 2.38
[0.22305788 0.77694212] 34
34 | 2.24
3
2.436666666666667


(array([[ 3,  0],
        [21, 12]]), (100.0, '%'))

In [245]:
conf_matrix(Mbig2,X_bigtest,y_bigtest,limite=0.5)

[0.34066358 0.65933642] 0
0 | 2.69
[0.26707404 0.73292596] 1
1 | 2.18
[0.21755485 0.78244515] 2
2 | 1.36
[0.29304897 0.70695103] 6
6 | 2.09 wrooooooooooooong
[0.4881345 0.5118655] 7
7 | 1.82
[0.45952375 0.54047625] 8
8 | 1.85 wrooooooooooooong
[0.21716474 0.78283526] 9
9 | 1.33 wrooooooooooooong
[0.37496866 0.62503134] 12
12 | 2.79
[0.4807712 0.5192288] 13
13 | 1.68 wrooooooooooooong
[0.46172089 0.53827911] 16
16 | 1.87
[0.11110225 0.88889775] 17
17 | 1.09
[0.37053841 0.62946159] 19
19 | 2.43
[0.26250667 0.73749333] 22
22 | 1.64 wrooooooooooooong
[0.39842668 0.60157332] 23
23 | 2.56
[0.47577204 0.52422796] 24
24 | 2.04 wrooooooooooooong
[0.31074917 0.68925083] 27
27 | 1.26
[0.39375072 0.60624928] 28
28 | 2.27
[0.30599628 0.69400372] 29
29 | 1.77 wrooooooooooooong
[0.43744616 0.56255384] 30
30 | 2.14
[0.28885205 0.71114795] 31
31 | 1.66
[0.48276493 0.51723507] 32
32 | 1.78
[0.36389826 0.63610174] 33
33 | 1.38
[0.36206761 0.63793239] 34
34 | 2.24
[0.4488969 0.5511031] 35
35 | 1.78
24
1.9

(array([[17,  7],
        [ 7,  5]]), (71.0, '%'))

In [160]:
biglion

Div       Date      Time             LO_Team             HO_Team  H/A  \
0      I1 2019-10-20     17:00               Parma               Genoa   10   
1      D1 2019-10-20  17:00:00          Schalke 04          Hoffenheim    0   
2     SP1 2019-10-20     17:30          Ath Bilbao          Valladolid   10   
3      I1 2019-10-20     19:45               Milan               Lecce   10   
4     SP1 2019-10-20     20:00             Sevilla             Levante   10   
5      F1 2019-10-20     20:00           Marseille          Strasbourg   10   
6      I1 2019-10-21     19:45          Fiorentina             Brescia    0   
7      E0 2019-10-21  20:00:00             Arsenal    Sheffield United    0   
8      D1 2019-10-25  19:30:00               Mainz             FC Koln   10   
9      I1 2019-10-25     19:45              Verona            Sassuolo   10   
10     F1 2019-10-25     19:45              Monaco              Nantes    0   
11    SP1 2019-10-25     20:00          Villarreal              Alaves   10   
12     E0 2019-10-25  20:00:00           Leicester         Southampton    0   
13     P1 2019-10-25     20:30             Rio Ave      Pacos Ferreira    0   
14     E0 2019-10-26  12:30:00            Man City         Aston Villa   10   
15     I1 2019-10-26     14:00            Juventus               Lecce    0   
16     D1 2019-10-26  14:30:00       Bayern Munich        Union Berlin   10   
17     D1 2019-10-26  14:30:00          RB Leipzig            Freiburg    0   
18     D1 2019-10-26  14:30:00              Hertha          Hoffenheim   10   
19     D1 2019-10-26  14:30:00           Paderborn  Fortuna Dusseldorf   10   
20     D1 2019-10-26  14:30:00            Dortmund          Schalke 04    0   
21    SP1 2019-10-26     15:00             Leganes            Mallorca   10   
22     E0 2019-10-26  15:00:00             Everton            Brighton    0   
23     E0 2019-10-26  15:00:00             Watford         Bournemouth   10   
24     E0 2019-10-26  15:00:00            West Ham    Sheffield United   10   
25     P1 2019-10-26     15:30          Belenenses                Aves   10   
26     P1 2019-10-26     15:30         Gil Vicente        Portimonense   10   
27     F1 2019-10-26     16:30               Lille            Bordeaux   10   
28     I1 2019-10-26     17:00               Inter               Parma   10   
29    SP1 2019-10-26     17:30          Valladolid               Eibar   10   
30     E0 2019-10-26  17:30:00             Chelsea             Burnley    0   
31     D1 2019-10-26  17:30:00          Leverkusen       Werder Bremen   10   
32     P1 2019-10-26     18:00             Setubal            Maritimo   10   
33     F1 2019-10-26     19:00               Brest               Dijon   10   
34     F1 2019-10-26     19:00                Lyon                Metz   10   
35     F1 2019-10-26     19:00         Montpellier              Angers   10   
36     F1 2019-10-26     19:00               Reims               Nimes   10   
37     F1 2019-10-26     19:00          Strasbourg                Nice   10   
38     I1 2019-10-26     19:45               Genoa             Brescia   10   
39    SP1 2019-10-26     20:00          Ath Madrid          Ath Bilbao   10   
40     P1 2019-10-26     20:30          Moreirense            Boavista   10   
41    SP1 2019-10-27     11:00            Sociedad               Celta    0   
42     I1 2019-10-27     11:30             Bologna           Sampdoria   10   
43    SP1 2019-10-27     13:00             Granada               Betis   10   
44     I1 2019-10-27     14:00            Atalanta             Udinese   10   
45     I1 2019-10-27     14:00              Napoli                Spal    0   
46     I1 2019-10-27     14:00              Torino            Cagliari   10   
47     F1 2019-10-27     14:00              Rennes            Toulouse   10   
48     E0 2019-10-27  14:00:00              Wolves           Newcastle    0   
49     D1 2019-10-27  14:30:00           Wolfsburg      

In [210]:
bigOdd=pd.read_excel('BigLion.xlsx',2)
XbigOdd=bigOdd.drop(['Div','Date','Time','LO_Team','HO_Team','Won/NotWon',],axis=1)
YbigOdd=bigOdd['Won/NotWon']
X_bigtrain=pd.concat([XbigOdd[:22],XbigOdd[23:]],sort=False)
y_bigtrain=pd.concat([YbigOdd[:22],YbigOdd[23:]],sort=False)
#X_oddtrain=XbigOdd[:31]
#y_oddtrain=YbigOdd[:31]
X_oddtest=XbigOdd.iloc[[22]]
y_oddtest=YbigOdd.iloc[[22]]

In [227]:
Modd1=SVC(C=1,kernel='rbf',probability=True)
Modd1.fit(X_oddtrain,y_oddtrain)

C:\Users\joaom\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=True, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [212]:
Modd2=Logit(C=0.0000001)
Modd2.fit(X_oddtrain,y_oddtrain)

C:\Users\joaom\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1e-07, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [209]:
conf_matrix(Modd2,X_oddtest,y_oddtest,limite=0.5)

[0.4995686 0.5004314] 0
0 | 1.17 wrooooooooooooong
1
1.17


(array([[0, 1],
        [0, 0]]), (0.0, '%'))

In [221]:
conf_matrix(Modd1,X_oddtest,y_oddtest,limite=0.5)

[0.03299957 0.96700043] 0
0 | 1.19
1
1.19


(array([[1, 0],
        [0, 0]]), (100.0, '%'))

In [205]:
Modd2.predict([[10,3,3,1.15,6.95,14.07,1.6,2.12,9,8,10.4,10.6,4.4,4.4,1.6,
                2,1.333,1,1,1,1,7,1,-18,10,9,4,4,1,2,0,1,13,0,10]])

array([1], dtype=int64)

In [220]:
Modd2.predict_proba([[10,3,3,1.15,6.95,14.07,1.6,2.12,9,8,10.4,10.6,4.4,4.4,1.6,
                2,1.333,1,1,1,1,7,1,-18,10,9,4,4,1,2,0,1,13,0,10]])

array([[0.49830198, 0.50169802]])

In [233]:
Modd2.predict_proba([[10,3,3,212.15,6.95,14.07,-1.6,-2.12,90,8,10.40,100.6,4.4,4.4,3.6,
                2,10.333,10,10,-1,-1,-7,-1,-18,-101,91,42,421,112,212,110,5,-2222222,0,-222222]])

array([[9.99954219e-01, 4.57807499e-05]])

In [ ]:
Modd2